### ISSUE TITLE
[Chapter1~3.4] 학습 내용 정리

### ISSUE THREAD

**Issue by zaragit** [Bom-start/ReadingRecord#14]
### 의견
1장에서 3.4장까지 내용에서 계속해서 DI와 IOC에 대한 설명이 나오고 있는 것 같아요.   
왜 개방-폐쇄 원칙(OCP)를 지켜야 하는지? OCP를 지키기 위해서 DI와 IOC를 통해 어떤 도움을 받을 수 있는지? 등...   
이해는 한 것 같은데 막상 글이나 말로 설명하려고 하면 자꾸만 다시 책을 보게 되네요... 😂
그래서 지금까지는 각자 학습한 내용을 정리했지만, 스터디 진행하면서 학습한 내용을 기록하는 차원에서 나중에 봐도 이해할 수 있도록 코드나 글의 형태로 한곳에 정리하고 넘어가면 좋을 것 같습니다!!    

제가 정리했으면 하는 내용입니다.  
**수정, 추가가 필요하다면 Issue 수정해 주셔도 되고, 필요 없다 생각되시면 Issue 닫아주셔도 됩니다!!**
1. 스프링에서 DI와 IOC
2. 개방-폐쇄 원칙(OCP)
3. 전략 패턴과 전략 패턴을 사용하면 좋은 점
4. 스프링은 왜 DI를 위해서 인터페이스를 사용하도록 강조하는지? 꼭 인터페이스로만 만들어야 하는지?

**Comment by youngjinmo** [comment]
좋은 방식같습니다. 저도 병주님이 정리하신 4가지 부분을 중심으로 정리해보겠습니다.
