### ISSUE TITLE
[Question]: 추상 데이터 타입과 클래스의 차이

### ISSUE THREAD

**Issue by youngjinmo** [Bom-start/ReadingRecord#88]
### Book

오브젝트

### Page

p.240 7.4장, 7.5장

## 추상 데이터 타입과 클래스의 차이가 명확하게 이해되지 않는다.
유연하게 선택해서 사용해야 한다고 저자는 설명하였으나 둘의 개념 차이를 명확하게 이해하지 못하여 어느상황에서 어떤 판단을 해야할지 이해하지 못하였습니다.
더 자세히 서술된 블로그 글이나 레퍼런스를 찾아보겠습니다!

**Comment by zaragit** [comment]
어렵게 이해한 내용을 까먹을까 봐 오전에 같이 리뷰했던 내용을 정리해 보았습니다!
수정할 내용이 없다면 이슈 close 부탁드립니다.


ADT와 OOP의 차이는 추상화와 분해 정도에 있다.

- **ADT:** 오퍼레이션을 기준으로 타입을 추상화
    - 타입이 Employee 타입 하나만 존재
    - 오퍼레이션 내에서 여러 타입을 통합(구별)
        - 구별은 인스턴스 변수로 처리(if문 사용)
    - ADT만 지원하는 언어에는 상속과 추상화 개념이 없다.
- **OOP:** 타입을 기준으로 절차들을 추상화
    - SalariedEmployee, HourlyEmployee 라는 클래스(타입)이 각각 실재
    - 각각 타입이 처리해야할 공동퇸 절차를 부모 타입(Employee)에 정의
        - 부모 타입을 통해서 if문 없이 여러 타입의 절차를 실행(다형성)

  
Java 언어를 기준으로 ADT ∈ OOP(ADT ≠ OOP)이다. OOP가 ADT의 개념을 포함하지만 ADT와 OOP가 동일하다고는 볼 수는 없다.


OOP를 지원하는 Java를 사용한다고 하더라도 상속과 다형성을 통해서 각각의 타입을 구분하지 않았다면 그것은 OOP가 아닌 ADT 추상화라고 봐야한다. 하지만 OOP가 무조건 좋은 방법인 것은 아니다. 각각의 장단점이 있다.

**ADT**
- **장점:** 오퍼레이션에 변경이 있어도 하나의 추상화 타입 내에서 처리할 수 있다.
- **단점:** 오퍼레이션이 아닌 새로운 타입이 추가되는 경우 if 분기문이 늘어나고 경우에 따라 if문에 필요한 인스턴스 변수가 더 필요할 수 있다.

**OOP**
- **장점:** 새로운 타입이 추가되면 기존에 타입은 건들 필요가 없이 새로운 클래스를 만들면 된다.
- **단점:** 오퍼레이션이 변경되면 타입의 갯수만큼 모든 클래스를 수정해야 한다.

결국 ADT나 OOP 중 어느 한 방식이 무조건 맞는게 아니다. 오퍼레이션과 타입 중 어느 쪽이 변경될 일 많은가에 따라서 ADT와 OOP 중 적절한 방식을 선택하면 된다.

**Comment by youngjinmo** [comment]
3일 지나서 다시 살펴보는데, 왜 또 새로운걸까요...ㅋㅋ

찾다보니 스택오버플로우에서 이런 질문글을 찾았습니다. (저희랑 똑같이 질문했네요..ㅋㅋ)
https://stackoverflow.com/questions/12982257/difference-between-abstract-data-type-and-object
